/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TahitiButton {
        "text": string;
    }
}
declare global {
    interface HTMLTahitiButtonElement extends Components.TahitiButton, HTMLStencilElement {
    }
    var HTMLTahitiButtonElement: {
        prototype: HTMLTahitiButtonElement;
        new (): HTMLTahitiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "tahiti-button": HTMLTahitiButtonElement;
    }
}
declare namespace LocalJSX {
    interface TahitiButton {
        "text"?: string;
    }
    interface IntrinsicElements {
        "tahiti-button": TahitiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tahiti-button": LocalJSX.TahitiButton & JSXBase.HTMLAttributes<HTMLTahitiButtonElement>;
        }
    }
}
